source "https://rubygems.org"

ruby '>= 3.3.0'

gem "fastlane"

# Add any other gems your Fastfile requires here
# For example:

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
